<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="utf-8">
	<TITLE>最近上映综艺,热门综艺,综艺下载 - 大饼影视 - </TITLE>
	<meta name="keywords" content="最近上映综艺,热门综艺,综艺下载">
	<meta name="description" content="">
	<link href="/favicon.ico" type="image/x-icon" rel="icon">
<link href="/favicon.ico" type="image/x-icon" rel="shortcut icon">
<link rel="stylesheet" href="/templets/id97/images/css/bootstrap.min.css">
<link rel="stylesheet" rev="stylesheet" type="text/css" media="all" href="/templets/id97/images/css/style.css">
<script src="/templets/id97/images/js/jquery.min.js"></script>
<script type="text/javascript">
try {
var urlhash = window.location.hash;
if (!urlhash.match("fromapp")) {
if ((navigator.userAgent.match(/(iPhone|iPod|Android|ios|iPad)/i))) {
window.location = "http://www.lookoro.cn/wap";
}
}
}
catch (err) {
}</script>
<script src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="/templets/id97/images/js/html5shiv.min.js"></script>
<script src="/templets/id97/images/js/respond.min.js"></script>
<![endif]-->
</head>
<body>
	<header style="background:#FFF;">

<div style="padding:5px 0;border-bottom:1px solid #DDD;">
    <div class="container">
        <span class="header-help">欢迎来到大饼影视，我们因为电影而相聚。</span>
        <div class="pull-right">
            <a class="header-help" href="javascript:alert('快捷键Ctrl+D可以快速添加到收藏夹。');">Ctrl+D 加入收藏夹</a> -
            <a class="header-help" style="color:red;" href="/desktop.php?url=http://http://m.yfmovie.top&name=大饼影视">保存到桌面</a>
        </div>
    </div>
</div>

<div class="container" style="padding-top:15px;padding-bottom:15px;padding-right:0;">
	<a class="logo pull-left" href="/"></a>
    <div class="pull-right" style="margin-top:8px;">
		<form class="navbar-form pull-right" accept-charset="utf-8" action="/search.php" method="POST" role="search">
            <div class="form-group">
				<input type="text" class="form-control" id="keyword" name="searchword" placeholder="请输入电影名字">
            </div><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span> 搜索</button>
        </form>
    </div>
</div>

<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <ul class="nav navbar-nav">
			<li id="index1" {if:3<0}class="active"{end if}><a href="/">首页</a></li>
			
			<li {if:1==3}class="active"{end if}><a target="_self" href="/list/?1.html">电影</a></li>
			
			<li {if:2==3}class="active"{end if}><a target="_self" href="/list/?2.html">电视剧</a></li>
			
			<li {if:3==3}class="active"{end if}><a target="_self" href="/list/?3.html">综艺</a></li>
			
			<li {if:4==3}class="active"{end if}><a target="_self" href="/list/?4.html">动漫</a></li>
			
<li id="index2"><a target="_self" href="/gbook.php">留言求片</a></li>
        </ul>
		<div class="pull-right">
			<ul class="nav navbar-nav">
                <li><a href="#">注册</a></li>
                <li><a href="#">登录</a></li>
			</ul>
		</div>
    </div>
</nav>

</header>
	<div class="container">
		<div class="row">
			<div class="tag-box">
				<table class="table" style="margin-bottom:10px;">
					<tbody>
						<tr>
							<td class="tag-span2">按剧情：</td>
							<td class="tags">
								<a href="#" class="tag active">全部</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E5%8E%86%E5%8F%B2" class="tag"> 历史</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E7%88%B1%E6%83%85" class="tag"> 爱情</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E7%8A%AF%E7%BD%AA" class="tag"> 犯罪</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E5%89%A7%E6%83%85" class="tag"> 剧情</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E6%AD%A6%E4%BE%A0" class="tag"> 武侠</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E5%8A%A8%E7%94%BB" class="tag"> 动画</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E6%96%87%E8%89%BA" class="tag"> 文艺</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E7%81%BE%E9%9A%BE" class="tag"> 灾难</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E7%A7%91%E5%B9%BB" class="tag"> 科幻</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E5%86%92%E9%99%A9" class="tag"> 冒险</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E9%83%BD%E5%B8%82" class="tag"> 都市</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E6%82%AC%E7%96%91" class="tag"> 悬疑</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E5%96%9C%E5%89%A7" class="tag"> 喜剧</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E5%A5%87%E5%B9%BB" class="tag"> 奇幻</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E5%8A%A8%E4%BD%9C" class="tag"> 动作</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E6%88%98%E4%BA%89" class="tag"> 战争</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E7%BB%8F%E5%85%B8" class="tag"> 经典</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E6%88%90%E9%95%BF" class="tag"> 成长</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E6%B2%BB%E6%84%88" class="tag"> 治愈</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E6%81%90%E6%80%96" class="tag"> 恐怖</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E6%83%85%E8%89%B2" class="tag"> 情色</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E8%B0%8D%E6%88%98" class="tag"> 谍战</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E6%83%8A%E6%82%9A" class="tag"> 惊悚</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E8%84%B1%E5%8F%A3%E7%A7%80" class="tag"> 脱口秀</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E7%9C%9F%E4%BA%BA%E7%A7%80" class="tag"> 真人秀</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E9%9D%92%E6%98%A5" class="tag"> 青春</a>
								
								<a href="/search.php?searchtype=5&tid=3&jq=%E5%8F%A4%E8%A3%85" class="tag"> 古装</a>
								
							</td>
						</tr>
						<tr>
							<td class="tag-span2">按地区：</td>
							<td class="tags">
								<a href="#" class="tag active">全部</a>
								 <a href='/search.php?searchtype=5&tid=3&area=%E5%A4%A7%E9%99%86' class="tag"> 大陆</a> <a href='/search.php?searchtype=5&tid=3&area=%E9%A6%99%E6%B8%AF' class="tag"> 香港</a> <a href='/search.php?searchtype=5&tid=3&area=%E5%8F%B0%E6%B9%BE' class="tag"> 台湾</a> <a href='/search.php?searchtype=5&tid=3&area=%E6%97%A5%E6%9C%AC' class="tag"> 日本</a> <a href='/search.php?searchtype=5&tid=3&area=%E9%9F%A9%E5%9B%BD' class="tag"> 韩国</a> <a href='/search.php?searchtype=5&tid=3&area=%E6%AC%A7%E7%BE%8E' class="tag"> 欧美</a> <a href='/search.php?searchtype=5&tid=3&area=%E6%B3%B0%E5%9B%BD' class="tag"> 泰国</a> <a href='/search.php?searchtype=5&tid=3&area=%E5%85%B6%E4%BB%96' class="tag"> 其他</a>          
							</td>
						</tr>
						<tr>
							<td class="tag-span2">按年代：</td>
							<td class="tags">			
								<a href="#" class="tag active">全部</a>
								 <a href='/search.php?searchtype=5&tid=3&year=2018' class="tag"> 2018</a>  <a href='/search.php?searchtype=5&tid=3&year=2017' class="tag"> 2017</a>  <a href='/search.php?searchtype=5&tid=3&year=2016' class="tag"> 2016</a>  <a href='/search.php?searchtype=5&tid=3&year=2015' class="tag"> 2015</a>  <a href='/search.php?searchtype=5&tid=3&year=2014' class="tag"> 2014</a>  <a href='/search.php?searchtype=5&tid=3&year=2013' class="tag"> 2013</a>  <a href='/search.php?searchtype=5&tid=3&year=2012' class="tag"> 2012</a>  <a href='/search.php?searchtype=5&tid=3&year=2011' class="tag"> 2011</a>  <a href='/search.php?searchtype=5&tid=3&year=2010' class="tag"> 2010</a>  <a href='/search.php?searchtype=5&tid=3&year=2009' class="tag"> 2009</a>  <a href='/search.php?searchtype=5&tid=3&year=2008' class="tag"> 2008</a>  <a href='/search.php?searchtype=5&tid=3&year=more' class="tag"> more</a> 
							</td>
						</tr>
					</tbody>
				</table>
			</div>

			<div class="col-xs-12" style="padding:0 5px;">
				{seacms:channellist size=35 order=time}
				<div class="col-xs-1-5 col-sm-4 col-xs-6 movie-item">
					<div class="movie-item-in">
						<a style="position:relative;display:block;" title="[channellist:name]" target="_blank" href="[channellist:link]">
							<img alt="[channellist:name]" title="[channellist:name]" src="[channellist:pic]">
							<span class="qtag">{if:[channellist:state]==0}[channellist:ver]{else}更新至[channellist:state]集{end if}</span>
							<div class="item-hover"></div>
						</a>
						<div class="meta">
							<h4><a href="[channellist:link]" target="_blank" title="[channellist:name]" class="movie-name">[channellist:name]</a><em> - [channellist:douban]分</em></h4>
							<div class="otherinfo">类型：[channellist:jqtype]</div>
						</div>    
					</div>
				</div>
				{/seacms:channellist}
			</div>
		</div>
		<div class="pager-bg" style="text-align:center;">
			<ul class="pagination pagination-sm">{if:{channellist:page}>1}<li><a href="{channellist:backlink}">上一页</a></li>{end if}
				{channellist:pagenumber len=8}
				<li {if:{channellist:page}=[pagenumber:page]}class="active"{end if}><a href="[pagenumber:link]">[pagenumber:page]</a></li>
				{/channellist:pagenumber}
				{if:{channellist:pagecount}>1}
				<li><a href="{channellist:nextlink}">下一页</a></li>
				<li><a href="{channellist:lastlink}">末页</a></li>
				{end if}
			</ul>
		</div>

	</div><!-- end container -->
	﻿<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-xs-4">
				<p>免责声明：</p>
				<p>本网站所有内容都是靠程序在互联网上自动搜集而来，仅供测试和学习交流。若侵犯了您的权益，请发邮件通知站长。</p>
			</div>
			<div class="col-xs-4">
				<p>联系方式：</p>
				<p>QQ：2189154548</p>
			</div>
			<div class="col-xs-4">
				<em>♥ <a href="/">大饼影视</a> - {seacms:runinfo}</em>
			</div>
		</div>
	</div>
</footer>

</body>
</html>