<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="shortcut icon" href="/favicon.ico" /><!-- 我添加的网页站标的ico图标，别的页面我也修复添加了 --> 
<title>喜剧片-大饼影视手机版</title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE10"/>
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
<link rel="stylesheet" href="/templets/aikanV1/images/iconfont.css" type="text/css"/>
<link rel="stylesheet" href="/templets/aikanV1/images/stui_block.css" type="text/css"/>
<link rel="stylesheet" href="/templets/aikanV1/images/stui_default.css" type="text/css"/>
<link rel="stylesheet" href="/templets/aikanV1/images/stui_custom.css" type="text/css"/>
<script type="text/javascript" src="/templets/aikanV1/images/jquery.min.js"></script>
<script type="text/javascript" src="/templets/aikanV1/images/stui_default.js"></script>
<script type="text/javascript">var sitePath='', siteUrl='http://m.yfmovie.top/wap', sitepath=''</script>
<!--[if lt IE 9]>
<script src="https://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
<header class="stui-header__top clearfix" id="header-top">
<div class="container">
	<div class="row">
		<div class="stui-header_bd clearfix">
			<div class="stui-header__logo">
				<a class="logo" href="/"></a>
			</div>
			<div class="stui-header__side">
				<ul class="stui-header__user">
					<!--<li class="hidden-xs"><a href="/login.php"><i class="icon iconfont icon-account"></i></a></li>
					-->
					<li class="visible-xs"><a class="open-popup" href="javascript:;"><i class="icon iconfont icon-viewgallery"></i></a></li>
				</ul>
				<div class="stui-header__search">
					<form name="formsearch" id="formsearch" action='/search.php' method="post" autocomplete="off">
						<input class="form-control" id="wd" placeholder="输入影片关键词..." name="searchword" type="text" id="keyword" required=""><input type="submit" id="searchbutton" value="" class="hide"><button class="submit" id="submit" onclick="$('#formsearch').submit();"><i class="icon iconfont icon-search"></i></button>
					</form>
				</div>
			</div>
			<ul class="stui-header__menu type-slide">
				<li {if:10=-444}class="active"{end if}><a href="/">首页</a></li>
				
				<li {if:1=10}class="active"{end if}><a href="/waplist/?1.html">电影</a></li>
				
				<li {if:2=10}class="active"{end if}><a href="/waplist/?2.html">电视剧</a></li>
				
				<li {if:3=10}class="active"{end if}><a href="/waplist/?3.html">综艺</a></li>
				
				<li {if:4=10}class="active"{end if}><a href="/waplist/?4.html">动漫</a></li>
				
				<!-- <li ><a href="/topic/?1.html">专题</a></li> -->
                <!-- <li ><a href="/ys/">备用站点</a></li> -->
			</ul>
		</div>
	</div>
</div>
</header>
<div class="popup clearfix">
	<div class="popup-head bottom-line">
		<h5 class="title pull-right">全部分类</h5>
		<a href="javascript:;" class="close-popup"><i class="icon iconfont icon-back"></i></a>
	</div>
	<div class="popup-body col-pd">
		<ul class="tag tag-type">
		
			<li class="col-xs-4"><a href="/waplist/?1.html">电影</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?2.html">电视剧</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?3.html">综艺</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?4.html">动漫</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?5.html">动作片</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?6.html">爱情片</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?7.html">科幻片</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?8.html">恐怖片</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?9.html">战争片</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?10.html">喜剧片</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?11.html">纪录片</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?12.html">剧情片</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?13.html">大陆剧</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?14.html">港台剧</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?15.html">欧美剧</a></li>
		
			<li class="col-xs-4"><a href="/waplist/?16.html">日韩剧</a></li>
		
		</ul>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="stui-pannel stui-pannel-bg clearfix">
			<div class="stui-pannel-box">
				<div class="stui-pannel_hd">
					<div class="stui-pannel__head active bottom-line clearfix">
						<h3 class="title"><img src="/templets/aikanV1/images/icon_25.png"/>喜剧片</h3>
						<ul class="nav nav-page pull-right">
							<li>{if:{channellist:page}==1}<a><i class="icon iconfont icon-back"></i></a>{else}<a href="{channellist:backlink}"><i class="icon iconfont icon-back"></i></a>{end if}</li>
							<li>{if:{channellist:page}=={channellist:pagecount}}<a><i class="icon iconfont icon-more"></i></a>{else}<a href="{channellist:nextlink}"><i class="icon iconfont icon-more"></i></a>{end if}</i></a></li>
						</ul>
						<span class="more text-muted pull-right hidden-xs">共有{channellist:recordcount}部影片，当前第{channellist:page}页</span>
					</div>{if:10>4}
					<ul class="stui-screen__list type-slide bottom-line-dot clearfix">
						<li><span class="text-muted">按分类</span></li>
						
						<li {subif:10==5}class="active"{end subif}><a href="/waplist/?5.html">动作片</a></li>
						
						<li {subif:10==6}class="active"{end subif}><a href="/waplist/?6.html">爱情片</a></li>
						
						<li {subif:10==7}class="active"{end subif}><a href="/waplist/?7.html">科幻片</a></li>
						
						<li {subif:10==8}class="active"{end subif}><a href="/waplist/?8.html">恐怖片</a></li>
						
						<li {subif:10==9}class="active"{end subif}><a href="/waplist/?9.html">战争片</a></li>
						
						<li {subif:10==10}class="active"{end subif}><a href="/waplist/?10.html">喜剧片</a></li>
						
						<li {subif:10==11}class="active"{end subif}><a href="/waplist/?11.html">纪录片</a></li>
						
						<li {subif:10==12}class="active"{end subif}><a href="/waplist/?12.html">剧情片</a></li>
						
					</ul>{else}
					<ul class="stui-screen__list type-slide bottom-line-dot clearfix">
						<li><span class="text-muted">按分类</span></li>
						
					</ul>{end if}
					<ul class="stui-screen__list type-slide bottom-line-dot clearfix">
						<li><span class="text-muted">按地区</span></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&area=%E5%A4%A7%E9%99%86" title="大陆">大陆</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&area=%E9%A6%99%E6%B8%AF" title="香港">香港</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&area=%E5%8F%B0%E6%B9%BE" title="台湾">台湾</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&area=%E6%97%A5%E6%9C%AC" title="日本">日本</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&area=%E9%9F%A9%E5%9B%BD" title="韩国">韩国</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&area=%E6%AC%A7%E7%BE%8E" title="欧美">欧美</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&area=%E6%B3%B0%E5%9B%BD" title="泰国">泰国</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&area=%E5%85%B6%E4%BB%96" title="其他">其他</a></li>
						
					</ul>
					<ul class="stui-screen__list type-slide clearfix">
						<li><span class="text-muted">按年份</span></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=2018" title="2018">2018</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=2017" title="2017">2017</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=2016" title="2016">2016</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=2015" title="2015">2015</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=2014" title="2014">2014</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=2013" title="2013">2013</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=2012" title="2012">2012</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=2011" title="2011">2011</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=2010" title="2010">2010</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=2009" title="2009">2009</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=2008" title="2008">2008</a></li>
						
						<li><a href="/search.php?searchtype=5&tid=10&year=more" title="more">more</a></li>
						
					</ul>
				</div>
				<div class="stui-pannel_bd">
					<ul class="stui-vodlist clearfix">
					{seacms:channellist size=30 order=time}
						<li class="col-md-6 col-sm-4 col-xs-3">
						<div class="stui-vodlist__box">
							<a class="stui-vodlist__thumb lazyload" href="[channellist:link]" title="[channellist:name]" data-original="[channellist:pic]"><span class="play hidden-xs"></span><span class="pic-text text-right">{if:[channellist:state]<1}[channellist:note]{elseif:[channellist:state]<1000 and [channellist:state]>0}更新至第[channellist:state]集{elseif:[channellist:state]>1000}第[channellist:state]期{elseif:[channellist:state]=0 and "[channellist:note]"=""}[channellist:note]{end if}</span></a>
							<div class="stui-vodlist__detail">
								<h4 class="title text-overflow"><a href="[channellist:link]" title="[channellist:name]">[channellist:name]</a></h4>
								<p class="text text-overflow text-muted hidden-xs">[channellist:nolinkactor]</p>
							</div>
						</div>
						</li>
					{/seacms:channellist}
					</ul>
				</div>
			</div>
		</div>
		<!-- 筛选列表 -->
		<ul class="stui-page text-center cleafix">
			<li>{if:{channellist:page}==1}<a>首页</a>{else}<a href="{channellist:firstlink}">首页</a>{end if}</li>
			<li>{if:{channellist:page}==1}<a>上一页</a>{else}<a href="{channellist:backlink}">上一页</a>{end if}</li>
			{channellist:pagenumber len=6}
			{if:{channellist:page}<>[pagenumber:page]}<li class="hidden-xs"><a href="[pagenumber:link]">[pagenumber:page]</a></li>{else}<li class="hidden-xs active"><a>[pagenumber:page]</a></li>{end if}
			{/channellist:pagenumber}
			<li class="active visible-xs"><span class="num">{channellist:page}/{channellist:pagecount}</span></li>
			<li>{if:{channellist:page}=={channellist:pagecount}}<a>下一页</a>{else}<a href="{channellist:nextlink}">下一页</a>{end if}</li>
			<li>{if:{channellist:page}=={channellist:pagecount}}<a>尾页</a>{else}<a href="{channellist:lastlink}">尾页</a>{end if}</li>
		</ul>
		<!-- 列表翻页-->
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="stui-foot clearfix">
			<div class="col-pd text-center hidden-xs">
			</div>
			<p class="bdsharebuttonbox text-center margin-0 hidden-sm hidden-xs">
				<strong>分享：</strong><!--注释前面的图标开始<span class="bds_shere"></span>注释结束--><a class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a class="bds_weixin" data-cmd="weixin" title="分享到微信"></a><a class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a><a class="bds_bdhome" data-cmd="bdhome" title="分享到百度新首页"></a><a class="bds_tqf" data-cmd="tqf" title="分享到腾讯朋友"></a><a class="bds_youdao" data-cmd="youdao" title="分享到有道云笔记"></a><a class="bds_more" data-cmd="more" title="更多"></a>
			</p>
          
          <p class="text-muted hidden-sm hidden-xs">本网站内容收集于互联网，《大饼影视手机版》不承担任何由于内容的合法性及健康性所引起的争议和法律责任。<br> 本站永久免费更新最新电影与剧集，欢迎大家使用并推荐朋友。</p>
			<p class="margin-0 text-muted">2017-2018
              <span> | </span> 
              视频总数：213
              <span> | </span>
              今天更新：22
              <span> | </span>
              {seacms:runinfo}</p>
          
			<!--底部大图片注释开始<p class="text-center hidden-xs">
				<a href="http://http://m.yfmovie.top/wap" target="_blank" title="大饼影视手机版"><img src="/templets/aikanV1/images/copy.png" width="150" height="48" alt="大饼影视手机版"/></a>
			</p>注释结束-->
			<!--底部版权注释开始，因为原来的版权只有手机才能看到<p class="text-muted text-center visible-xs">Copyright © 2015-2018  All Rights Reserved</p>注释结束-->
		</div>
	</div>
</div>
<ul class="stui-extra clearfix">
	<li><a class="backtop" href="javascript:scroll(0,0)" style="display: none;"><i class="icon iconfont icon-less"></i></a></li>
	<li class="visible-xs"><a class="open-share" href="javascript:;"><i class="icon iconfont icon-share"></i></a></li>
	<li class="hidden-xs"><span><i class="icon iconfont icon-qrcode"></i></span>
	<div class="sideslip">
		<div class="col-pd">
			<img class="qrcode" width="150" height="150"/>
			<p class="text-center font-12">
				<strong>手机扫码访问这个页面</strong>
			</p>
		</div>
	</div>
	</li>
</ul>
<div class="hide">
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?951e1c4e49fc2c956865811f5f7a4d84";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

</div>
<script type="text/javascript" charset="utf-8">
	window._bd_share_config = {
		common: {
			bdText: '',
			bdDesc: '',
			bdUrl: '',
			bdPic: ''
		},
		share: [{
			"bdSize": 24,
			bdCustomStyle: '/templets/aikanV1/images/stui_default.css'
		}]
	}
	with(document) 0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?cdnversion=' + ~(-new Date() / 36e5)];
</script>
</body>
</html>